# Name of the Project
PROJECT_NAME = Snake and Ladder

#Output directory
BUILD        = build
SRCDIR     	 = src
SRCTESTDIR	 = test
OBJDIR    	 = obj
BINDIR    	 = bin
INCDIR	  	 = include

CC       = gcc
#compiling flags here
#CFLAGS   = -Wall

.PHONY: clean
clean:
	@$(rm) $(OBJECTS1) $(BINDIR)/$(TARGET)
	@$(rm) $(OBJECTS2) $(BINDIR)/$(TARGET_TEST)
	@echo "Cleanup complete!"
